# Generated by Django 5.1 on 2025-03-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default=1, upload_to='imag-contact'),
            preserve_default=False,
        ),
    ]
