# Generated by Django 5.1 on 2025-05-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
