# Generated by Django 4.2.25 on 2025-11-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_category_project_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Gig', 'verbose_name_plural': 'Gigs'},
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_time',
            field=models.PositiveIntegerField(default=3, help_text='Delivery time in days'),
        ),
        migrations.AddField(
            model_name='project',
            name='offers_consultation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='packages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='revisions',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
